name: yasmin_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.14
  dio: ^5.0.0
  shared_preferences: ^2.1.0
  fluttertoast: ^8.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1
  intl: ^0.18.1
  url_launcher: ^6.1.5
  flutter_native_splash: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.0
  hive_generator: ^1.1.0
  flutter_launcher_icons: "^0.13.1"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/bc30.jpg
    - assets/bc34.jpg
    - assets/bc32.jpg
    - assets/bc31.jpg
    - assets/bc10.jpg
    - assets/bc11.jpg
    - assets/bc12.jpg
    - assets/bc14.jpg
flutter_native_splash:

  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
  # dart run flutter_native_splash:remove --path=flutter_native_splash.yaml

  color: "#D4AF37"
  image: "assets/logo.png"
  color_dark: "#363636"
  image_dark: "assets/logo.png"

  android_12:
    color: "#D4AF37"
    image: "assets/logo.png"
    color_dark: "#363636"
    image_dark: "assets/logo.png"

  web: false